### PR TITLE
Makefile and readme updates

### PR DESCRIPTION
**Pull request by ghost**
I've updated `Makefile` and `ota.c` so they should properly compile now. Additionally, I've updated the readme so it contains less typos and links to the original source files (pbzx.c, ota.c, etc.)

### CODE REVIEW

**Comment by matteyeux** [comment]
Thank you, merged !

**Comment by georgeedwardg** [comment]
Not working for me.

> Building pbzx...
02_decompress.c:22:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^~~~~~~~
1 error generated.
make: *** [pbzx] Error 1

UPDATE: Fixed by running 
> brew install xz

prior to

> make

**Comment by ghost** [comment]
Oops! I’ll get to creating another PR tomorrow adding brew install instructions. Got to sleep soon... 😴

**Comment by georgeedwardg** [comment]
Updated my previous comment too soon... unable to decompress payload2.xz file

I suspect something is wrong with the pbzx?

> Building pbzx...
02_decompress.c:273:17: warning: assigning to 'const uint8_t *' (aka
      'const unsigned char *') from 'const char *' converts between pointers to
      integer types with different sign [-Wpointer-sign]
                strm->next_in = inbytes;
                              ^ ~~~~~~~
02_decompress.c:372:1: warning: control may reach end of non-void function
      [-Wreturn-type]
}
^
2 warnings generated.
Successfully built pbzx
Building imagine...
Successfully built imagine
Building ota...
ota.c:269:6: warning: format specifies type 'unsigned long long' but the
      argument has type 'int' [-Wformat]
                                        relOffset,
                                        ^~~~~~~~~
1 warning generated.
Successfully built ota

**Comment by ghost** [comment]
What’s the specific error when running pbzx? Can you give some sample output and describe what OTA firmware you’re testing on?

**Comment by georgeedwardg** [comment]
iOS OTA 9.9.11.0.2 (15C25)

I noticed you updated a few files last night, so I tried to re-compile and decompress just now.  No joy.

**Comment by ghost** [comment]
What error do you get by running `pbzx` on `payload.xz`?

**Comment by georgeedwardg** [comment]
> xz: payload2.xz: File format not recognized

**Comment by georgeedwardg** [comment]
Oh and if sample output helps... here you go:

> $ ./pbzx < payload > payload2.xz
Flags: 0x1000000
Chunk #1 (flags: 1000000, length: 3343604 bytes) 
OK!  (16777216 bytes)
Chunk #2 (flags: 1000000, length: 5881856 bytes) 
OK!  (16777216 bytes)
Chunk #3 (flags: 1000000, length: 10237140 bytes) 
OK!  (16777216 bytes)
Chunk #4 (flags: 1000000, length: 9234680 bytes) 
OK!  (16777216 bytes)
Chunk #5 (flags: 1000000, length: 8593528 bytes) 
OK!  (16777216 bytes)
Chunk #6 (flags: 1000000, length: 6878044 bytes) 
OK!  (16777216 bytes)
Chunk #7 (flags: 1000000, length: 4994232 bytes) 
OK!  (16777216 bytes)
Chunk #8 (flags: 1000000, length: 4481088 bytes) 
OK!  (16777216 bytes)

Quite a few do come back w/ this error which I suspect is normal

> Chunk #86 (flags: 1000000, length: 16777216 bytes) 
Warning: Can't find XZ header. Instead have 0x13f7a329(?).. This is likely not XZ data.

**Comment by ghost** [comment]
Okay, any other errors? Did you try `xz --decompress payload2.xz` yet?

**Comment by georgeedwardg** [comment]
Yup.  That's precisely where I'm stuck

> $ xz --decompress payload2.xz
xz: payload2.xz: File format not recognized

Strange.

Oh and to confirm brew and xz are installed

> $ brew install xz
Warning: xz 5.2.3 is already installed

**Comment by ghost** [comment]
To confirm, does the firmware zip file return the following hashes?

```
SHA1: 7b3447ba4bb08efd139f74b23442e52cd19157d1
SHA256: 4d864a6d59d83b2e09ebc54848cf73c07a737d0d602e982e995e7ed45b668a8e
```

**Comment by georgeedwardg** [comment]
I can't be sure.  Extracted and got rid of the original zip.  Let me dig up a Time Machine backup and double-check.

**Comment by ghost** [comment]
Okay. Please note: if you just recently downloaded the zip file, don’t even bother. Apple began encrypting it with OpenSSL a few days ago.

**Comment by georgeedwardg** [comment]
I downloaded the file on 8/2, so I don't believe that is the culprit.

UPDATE:  I don't have the original zip, but the unzipped contents root folder name is:
6841e048050f1f38ecc68977bbdc76d746da6559.

**Comment by ghost** [comment]
hashes for `payload`:

```
SHA1: 00f2a3aa5cd82c73f6e8b8f6c1a36230c3ea0c73
SHA256: 5f9fa4ad366d1e2f46f07f5f617134e5a130e4c87b9660963211527615dc1a21
```

**Comment by georgeedwardg** [comment]
SHA1: 00f2a3aa5cd82c73f6e8b8f6c1a36230c3ea0c73

Confirmed.

**Comment by ghost** [comment]
Hm. `pbzx` returns "Killed" right before it is about to be finished. Not good...

**Comment by georgeedwardg** [comment]
Hm indeed.  Explains why decompression fails.  Do you suspect our friends in Cupertino have implemented this via an XProtect update?

I'm puzzled.

**Comment by ghost** [comment]
No. The updated code in pbzx.c is the culprit. I tested the older version on Linux, and it worked beautifully. The newer version was *supposed* to improve compatibility with HomePod FW, but ended up doing exactly the opposite. I've created #2, which reverts back to the latest known working version.

Edit: Do you mind trying [my fork?](https://github.com/citrusui/iOS-Utilities) It should work as expected.

**Comment by matteyeux** [comment]
hey @citrusui and @georgeedwardg have you tried pre-built binaries from [newosxbook](http://newosxbook.com/code/listings/pbzx.tar) ?

**Comment by georgeedwardg** [comment]
@citrusui Hah.  I'm always trying to find a way to blame XProtect.  Attempted w/ your fork and pbzx ran w/out incident.  Decompressing is in progress now, so would appear to be working.

@matteyeux Nope.

**Comment by matteyeux** [comment]
Ok now merging #2

**Comment by ghost** [comment]
@matteyeux the pre-built binaries do not work.

I find it a little silly that you pushed these changes without testing them. As it stands, the code in this repo doesn't work at all :disappointed: 

Tried contacting J Levin, but he hasn't responded yet.

**Comment by matteyeux** [comment]
My bad, I was hurry when I pushed the code and did't find time to test :/

**Pull request merged**
